/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.claudemirovsky.undetektedchromedriver

import kotlin.test.Test

class UndetektedChromeDriverTest {
    @Test fun testDriver() {}
}
